language: node_js
node_js:
  - "9.11"

install:
  - yarn install

cache:
  directories:
    - "node_modules"

script:
#  - yarn test
  - yarn build
  # - echo my-custom-domain.ru > build/CNAME

after_success:
- curl --ftp-create-dirs -T dist/lib.js sftp://${SELCDN_USER}:${SELCDN_PASS}@ftp.selcdn.ru/rockstat/dist/
