language: node_js
node_js:
  - "9.11"

install:
  - yarn install

cache:
  directories:
    - "node_modules"


script:
  - yarn test
  - yarn build
  - echo my-custom-domain.ru > build/CNAME

after_success:
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- curl --ftp-create-dirs
       -T filename
       --key /tmp/sftp_rsa
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@example.com/directory/filename
